### ISSUE TITLE
Our first ODM lab

### ISSUE THREAD

**Issue by VanderY** [comoediis/ODM#1]
Suka nado sdelat labu do chetverga inache nam pizda

**Comment by comoediis** [comment]
О привет.

пн, 9 мар. 2020 г., 16:06 VanderY <notifications@github.com>:

**Comment by comoediis** [comment]
Третьего дня, по совету проверенных камрадов, приобрёл новый мегадевайс — Анальную пробку «Сталин-3000». Сразу же, задыхаясь от жадности, вскрыл коробку цепкими лапами и заюзал мегадевайс. Размер, моё почтение. Настоящей глыбой был Иосиф Виссарионович. Даже моя, привыкшая к суровым армейским будням, жопа, отказывалась принимать с первого захода. Совместными с Олегом Зотовым усилиями забороли проблему. Ощущения — АТАС. С автоматом не идёт ни в какое сравнение. Кроме того, усы приятно щекочут простату. Проходил так весь день. Решительно готов к съёмкам новой б/ездуховности.
Многие дети увидят тут проявления гомосексуализма. Тупым детям невдомёк, что педерастия и патриотизм — это разные вещи.
Девайс отличный, всем рекомендую к приобретению.
Всё это, как водится, реклама.

**Comment by VanderY** [comment]
пепси)
